### ISSUE TITLE
[Client] client 기본 세팅

### ISSUE THREAD

**Issue by hyeonjeongchung** [codestates/SAFU-client#2]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: react create app, 전체 컴포넌트 구성

### TODO
1. [x] 맞출 기본 세팅 확인 - 다같이
2. [x] react create app
3. [x] 파일 구성 등  전체 컴포넌트 구성

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 0.5h`
- Group : `client`
- Sprint: `Sprint__1__`
- Urgency: `High`
