### ISSUE TITLE
[Client]logout

### ISSUE THREAD

**Issue by hyeonjeongchung** [codestates/SAFU-client#44]
### ISSUE
- Group:  `client`
- Type:`feature`
- Detail: logout 기능 구현

### TODO
1. [x] Nav 컴폰넌트에 logout 버튼 넣기
2. [x] logout버튼 클릭시 세션 제거하기
3. [x] 그 후 바로 login 안된 main 페이지로 리다이렉트 시키기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__1__`
- Urgency: `High`
