### ISSUE TITLE
[Client] Routing 과 Redirecting 정리

### ISSUE THREAD

**Issue by hyeonjeongchung** [codestates/SAFU-client#80]
### ISSUE
- Group:  `client`
- Type: `fix`
- Detail: 현재 라우팅 및 리다이렉팅이 너무 정신없게 되어있는 것 같아 이를 좀 정리하려고 합니다. 

### TODO
1. [x] Nav.js 의 라우팅을 정리한다. 
2. [x] 모든 기능이 정상 라우팅 되는지 확인한다. 
3. [x] 모든 기능에서 정상 리다이렉팅이 되는지 확인한다. 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__1__`
- Urgency: `Middle`
